In [1]:
import pandas as pd
import requests
#!pip install yfinance
import yfinance as yf

In [2]:
# Loading Fear and Greed Index data via API and converting to a DataFrame
url = requests.get('https://api.alternative.me/fng/?limit=0')
data = url.json()['data']
df = pd.DataFrame(data)
df.head()

  value value_classification   timestamp time_until_update
0    10         Extreme Fear  1772409600             20570
1    14         Extreme Fear  1772323200               NaN
2    11         Extreme Fear  1772236800               NaN
3    13         Extreme Fear  1772150400               NaN
4    11         Extreme Fear  1772064000               NaN

In [3]:
# Checking data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2948 entries, 0 to 2947
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   value                 2948 non-null   object
 1   value_classification  2948 non-null   object
 2   timestamp             2948 non-null   object
 3   time_until_update     1 non-null      object
dtypes: object(4)
memory usage: 92.3+ KB

In [22]:
# Changing data types
df['timestamp'] = pd.to_numeric(df['timestamp'])
df['timestamp'] = pd.to_datetime(df['timestamp'], unit = 's')
df['value'] = df['value'].astype(int)

In [23]:
df.tail(5)

      value value_classification  timestamp time_until_update
2943     11         Extreme Fear 2018-02-05               NaN
2944     24         Extreme Fear 2018-02-04               NaN
2945     40                 Fear 2018-02-03               NaN
2946     15         Extreme Fear 2018-02-02               NaN
2947     30                 Fear 2018-02-01               NaN

In [6]:
# Loading BTC price data
btc_finance = yf.download ('BTC-USD', start = '2018-02-05')
btc_finance.head()

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open       Volume
Ticker          BTC-USD      BTC-USD      BTC-USD      BTC-USD      BTC-USD
Date
2018-02-05  6955.270020  8364.839844  6756.680176  8270.540039   9285289984
2018-02-06  7754.000000  7850.700195  6048.259766  7051.750000  13999800320
2018-02-07  7621.299805  8509.110352  7236.790039  7755.490234   9169280000
2018-02-08  8265.589844  8558.769531  7637.859863  7637.859863   9346750464
2018-02-09  8736.980469  8736.980469  7884.709961  8271.839844   6784820224

In [7]:
# Formatting data to extract columns for analysis
btc = btc_finance.reset_index()

In [8]:
btc.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']

In [19]:
btc.head()

        Date        Close         High          Low         Open       Volume
0 2018-02-05  6955.270020  8364.839844  6756.680176  8270.540039   9285289984
1 2018-02-06  7754.000000  7850.700195  6048.259766  7051.750000  13999800320
2 2018-02-07  7621.299805  8509.110352  7236.790039  7755.490234   9169280000
3 2018-02-08  8265.589844  8558.769531  7637.859863  7637.859863   9346750464
4 2018-02-09  8736.980469  8736.980469  7884.709961  8271.839844   6784820224

In [10]:
# Checking data types
btc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2948 entries, 0 to 2947
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    2948 non-null   datetime64[ns]
 1   Close   2948 non-null   float64
 2   High    2948 non-null   float64
 3   Low     2948 non-null   float64
 4   Open    2948 non-null   float64
 5   Volume  2948 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 138.3 KB

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2948 entries, 0 to 2947
Data columns (total 4 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   value                 2948 non-null   int64
 1   value_classification  2948 non-null   object
 2   timestamp             2948 non-null   datetime64[ns]
 3   time_until_update     1 non-null      object
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 92.3+ KB

In [24]:
# Merging data into a single DataFrame
df_final = pd.merge(df, btc, left_on = 'timestamp', right_on = 'Date')
df_final.head()

,value,value_classification,timestamp,time_until_update,Date,Close,High,Low,Open,Volume
0,10,Extreme Fear,2026-03-02,20570,2026-03-02,69094.304688,69882.335938,65370.769531,65758.101562,55519461376
1,14,Extreme Fear,2026-03-01,NaN,2026-03-01,65738.101562,68162.820312,65076.730469,67005.882812,40733141929
2,11,Extreme Fear,2026-02-28,NaN,2026-02-28,66995.859375,67714.523438,63062.218750,65878.929688,42041497112
3,13,Extreme Fear,2026-02-27,NaN,2026-02-27,65881.796875,68220.406250,64946.035156,67456.515625,40283655942
4,11,Extreme Fear,2026-02-26,NaN,2026-02-26,67453.773438,68843.351562,66523.734375,67954.867188,42988597523

In [13]:
# Removing unnecessary columns
df_final = df_final.drop(columns = ['time_until_update', 'Date'])

In [25]:
df_final.columns = df_final.columns.str.lower()
df_final.head()

,value,value_classification,timestamp,time_until_update,date,close,high,low,open,volume
0,10,Extreme Fear,2026-03-02,20570,2026-03-02,69094.304688,69882.335938,65370.769531,65758.101562,55519461376
1,14,Extreme Fear,2026-03-01,NaN,2026-03-01,65738.101562,68162.820312,65076.730469,67005.882812,40733141929
2,11,Extreme Fear,2026-02-28,NaN,2026-02-28,66995.859375,67714.523438,63062.218750,65878.929688,42041497112
3,13,Extreme Fear,2026-02-27,NaN,2026-02-27,65881.796875,68220.406250,64946.035156,67456.515625,40283655942
4,11,Extreme Fear,2026-02-26,NaN,2026-02-26,67453.773438,68843.351562,66523.734375,67954.867188,42988597523

In [15]:
# Calculating summary statistics for overview
analysis = df_final.groupby('value_classification')['close'].mean().sort_values()
analysis

Series([], Name: close, dtype: float64)

In [16]:
# Saving the final file
df_final.to_excel(r'C:\Users\PC\Desktop\google trends\btc_analysis.xlsx', index=False)